name: kvmtool build

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ inputs.branch }}
  cancel-in-progress: true
  
permissions:
  contents: write
  
jobs:
  prepare:
    runs-on: self-hosted

    steps:
      - name: Checkout caller repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ inputs.branch }}
          submodules: recursive
          clean: true
          path: kvmtool
          
  build:
    needs: prepare
    uses: ./.github/workflows/build-and-snapshot.yml
    with:
      build_script: build-kvmtool.sh
      artifact_name: kvmtool-snapshot
      artifact_path: snapshot/lkvm
      upload_artifact: true
      release_artifact: true
      release_name: kvmtool

