name: kvmtool build

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ inputs.branch }}
  cancel-in-progress: true


jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout caller repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ inputs.branch }}
          submodules: recursive
          clean: true
          path: kvmtool
          
      - name: Build and snapshot artifact
        uses: ./.github/workflows/build-and-snapshot.yml
        with:
          build_script: build-kvmtool.sh
          artifact_name: kvmtool-snapshot
          artifact_path: snapshot/lkvm
          upload_artifact: true
          release_artifact: true
          release_name: kvmtool

      # - name: Run build script
      #   run: |
      #     rm -rf .ci || true
      #     git clone --depth 1 "$CI_REPO" .ci
      #     cd .ci
      #     ./"$CI_RUN_SCRIPT" "$GITHUB_WORKSPACE" ./"$CI_BUILD_SCRIPT"
    
      # - name: Upload snapshot
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: kvmtool-snapshot
      #     path: snapshot/lkvm
      #     if-no-files-found: error



